### ISSUE TITLE
Display text in sans-serif font

### ISSUE THREAD

**Issue by rmccue** [tomv564/LSP#82]
VS Code's overlays use sans-serif fonts for regular text within overlays. It would be neat if we could do the same here.

(e.g. https://code.visualstudio.com/images/intellisense_paramater_info.png)

Given that this is potentially down to user preference, this could be a preference rather than a default.

(This is already possible through mdpopups' [user CSS preference](http://facelessuser.github.io/sublime-markdown-popups/settings/#mdpopupsuser_css), but IMO would make a good default.)

**Comment by tomv564** [comment]
Would be nice to see some screenshots on multiple platforms of what a "default" sans-serif font stack would look like!

**Comment by rmccue** [comment]
On macOS:

<img width="627" alt="screenshot 2017-09-08 17 29 40" src="https://user-images.githubusercontent.com/21655/30200694-56dbffbc-94bb-11e7-9f9a-fd1c97632e62.png">

(Don't have my Windows machine handy currently, but I can get a screenshot for that later.)

You can try this locally with the following in `Packages/Users/mdpopups.css`:

```css
.mdpopups .lsp_hover {
	font-family: sans-serif;
	line-height: 1.4em;
}

.lsp_hover div.highlight,
.lsp_hover pre.highlight {
	margin-bottom: 0;
}
```
